### ISSUE TITLE
Invalid Impl

### ISSUE THREAD

**Issue by luxdlzu** [faa-swim/swim-discovery-service#10]
File: sdm-j/1.0.0/profile.json
Line:
L.130: "calculation method",
L.131: "unit of measure"

Should be:
L.130: "calculation-method",
L.131: "unit-of-measure"

**Comment by cinglefield** [comment]
Please see current profile.json in Github - this has been fixed

**Comment by wznira** [comment]
Version 1.0.1 of the schema published on discovery.swim.aero/sdm-j

**Comment by wznira** [comment]
Version 1.0.1 of the schema published on discovery.swim.aero/sdm-j

**Comment by luxdlzu** [comment]
This bug is not revised in the new version.

File: sdm-j/1.0.1/profile.json
Line:
L.126: "required": [ "name", "value", "description", "calculation method", "unit of measure" ]

Should be:
"required": [ "name", "value", "description", "calculation-method", "unit-of-measure" ]

**Comment by wznira** [comment]
Updated on discovery.swim.aero.
