### ISSUE TITLE
Wrong definition in sds/1.0.1/sds.json

### ISSUE THREAD

**Issue by luxdlzu** [faa-swim/swim-discovery-service#15]
In the schema, sds/1.0.1/sds.json, the definition of a query parameter for API to get service is not correct.

Wrong:
          {
            "name": "service-product",
            "in": "query",
            "description": "Values as defined in http://semantics.aero/service-product",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }

Correct:
          {
            "name": "service-category",
            "in": "query",
            "description": "Values as defined in http://semantics.aero/service-category",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }

**Comment by caroluri** [comment]
The [schema](https://discovery.swim.aero/sds/1.0.1/sds.json) is referring to an older similar taxonomy on [https://semantics.aero](https://semantics.aero), SWIM Service Product, instead of the correct one which is SWIM Service Category. Agree that the schema should be changed.

**Comment by wznira** [comment]
Will update the schema

**Comment by wznira** [comment]
JSON schemas have been updated on https://discovery.swim.aero/sds/1.0.1/
