### ISSUE TITLE
Invalid Impl

### ISSUE THREAD

**Issue by luxdlzu** [faa-swim/swim-discovery-service#7]
File: services.json
Line: L.65
Code:
--------
    "code": {
        "type": "string",
        }
--------

Should be:
--------
    "code": {
        "type": "string"
        }
--------
or
--------
    "code": {
        "type": "string",
        "format": "uri"
        }
--------

**Comment by cinglefield** [comment]
Fixed

**Comment by wznira** [comment]
Version 1.0.1 of the schema published on discovery.swim.aero/sdm-j
