### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by luxdlzu** [faa-swim/swim-discovery-service#8]
I cannot get the model.json from the following $ref.
 "$ref": "https://semantics.aero/service-description/sdm-j/sdm-j-1.0.0/****.json"
(404 Not Found)

**Comment by cinglefield** [comment]
What file is this $ref in? "$ref": "https://semantics.aero/service-description/sdm-j/sdm-j-1.0.0/****.json"

**Comment by luxdlzu** [comment]
What I want to say is that I cannot use "$ref": "https://semantics.aero/service-description/sdm-j/sdm-j-1.0.0/****.json" as the outside reference to access the files of sdm-j/1.0.0/*.json.

Moreover, in the file discovery-service.json, the following $ref is not correct.
Line: L.29
"$ref": "https://discovery.swim.aero/sdm-j/1.0.0/organization.json"

Should be:
 "$ref": "https://discovery.swim.aero/sdm-j/1.0.0/organization.json#/definitions/organization"

**Comment by cinglefield** [comment]
Thank you - fixed $ref in Github discovery-service.json

**Comment by wznira** [comment]
Version 1.0.1 of the schema published on discovery.swim.aero/sdm-j
